# set default-terminal colors to display default terminal colors

set -g default-terminal "xterm-256color"

# set-option -ga terminal-overrides ',xterm-256color:Tc

# Proper colors

set-option -sa terminal-features ',xterm-256color:RGB'

# &#x200B;

# Undercurl

# Set the default terminal mode to 256 colors
set -g default-terminal "tmux-256color"

# Enable RGB (true color) support
# NOTE: The "xterm-kitty" part must match your OUTSIDE terminal's $TERM
set -as terminal-features ",xterm-kitty:RGB"

set-option -g renumber-windows on

set -s set-clipboard on

set-window-option -g mode-keys vi

