local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

local _1XC3_template = t(
    {
        [[\documentclass[12pt]{article}]],
        [[\usepackage{ragged2e} % load the package for justification]],
        [[\usepackage{hyperref}]],
        [[% to remove the hyperline rectangle]],
        [[\hypersetup{]],
        [[colorlinks=true,]],
        [[linkcolor=orange!80!black, % Set the link color to blue]],
        [[urlcolor=blue,  % Set the URL color to blue]],
        [[citecolor=blue, % Set the citation color to blue]],
        [[}]],
        [[]],
        [[\usepackage[utf8]{inputenc}]],
        [[]],
        [[]],
        [[\usepackage{pgfplots}]],
        [[\usepackage{tikz}]],
        [[\usepackage{pgf-pie}]],
        [[\usetikzlibrary{pgfplots.statistics}]],
        [[]],
        [[]],
        [[\usepackage{filecontents}]],
        [[\usepackage{multirow}]],
        [[\usepackage{amsmath}]],
        [[\pgfplotsset{width=10cm,compat=1.17}]],
        [[\setlength{\parskip}{0.75em} % Set the space between paragraphs]],
        [[\usepackage{setspace}]],
        [[\setstretch{1.2} % Adjust the value as per your preference]],
        [[\usepackage[margin=2cm]{geometry} % Adjust the margin]],
        [[\setlength{\parindent}{0pt} % Adjust the value for starting paragraph]],
        [[]],
        [[\usepackage{mdframed}]],
        [[]],
        [[]],
        [[\usepackage{xcolor}]],
        [[\usepackage{titlesec}]],
        [[\usepackage{titletoc}]],
        [[\usepackage{listings}]],
        [[\usepackage{tcolorbox}]],
        [[\usepackage{lipsum} % Example text package]],
        [[\usepackage{fancyhdr} % Package for customizing headers and footers]],
        [[]],
        [[]],
        [[]],
        [[% Define the orange color]],
        [[\definecolor{myorange}{RGB}{255,65,0}]],
        [[% Define a new color for "cherry" (dark red)]],
        [[\definecolor{cherry}{RGB}{148,0,25}]],
        [[\definecolor{codegreen}{rgb}{0,0.6,0}]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%]],
        [[% Apply the custom footer to all pages]],
        [[\pagestyle{fancy}]],
        [[]],
        [[% Redefine the header format]],
        [[\fancyhead{}]],
        [[\fancyhead[R]{\textcolor{orange!80!black}{\itshape\leftmark}}]],
        [[]],
        [[\fancyhead[L]{\textcolor{black}{\thepage}}]],
        [[]],
        [[]],
        [[% Set the header rule color to orange]],
        [[\renewcommand{\headrule}{\color{orange!80!black}\hrule width\headwidth height\headrulewidth \vskip-\headrulewidth}]],
        [[]],
        [[% Set the footer rule color to orange (optional)]],
        [[\renewcommand{\footrule}{\color{black}\hrule width\headwidth height\headrulewidth \vskip-\headrulewidth}]],
        [[]],
        [[%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%]],
        [[]],
        [[% Set the color for the section headings]],
        [[\titleformat{\section}]],
        [[{\normalfont\Large\bfseries\color{orange!80!black}}{\thesection}{1em}{}]],
        [[]],
        [[% Set the color for the subsection headings]],
        [[\titleformat{\subsection}]],
        [[{\normalfont\large\bfseries\color{orange!80!black}}{\thesubsection}{1em}{}]],
        [[]],
        [[% Set the color for the subsubsection headings]],
        [[\titleformat{\subsubsection}]],
        [[{\normalfont\normalsize\bfseries\color{orange!80!black}}{\thesubsubsection}{1em}{}]],
        [[]],
        [[]],
        [[%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%]],
        [[% Set the color for the table of contents]],
        [[\titlecontents{section}]],
        [[[1.5em]{\color{orange!80!black}}]],
        [[{\contentslabel{1.5em}}]],
        [[{}{\titlerule*[0.5pc]{.}\contentspage}]],
        [[]],
        [[% Set the color for the subsections in the table of contents]],
        [[\titlecontents{subsection}]],
        [[[3.8em]{\color{orange!80!black}}]],
        [[{\contentslabel{2.3em}}]],
        [[{}{\titlerule*[0.5pc]{.}\contentspage}]],
        [[]],
        [[% Set the color for the subsubsections in the table of contents]],
        [[\titlecontents{subsubsection}]],
        [[[6em]{\color{orange!80!black}}]],
        [[{\contentslabel{3em}}]],
        [[{}{\titlerule*[0.5pc]{.}\contentspage}]],
        [[]],
        [[]],
        [[%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%]],
        [[% set a format for the codes inside a box with C format]],
        [[\lstset{]],
        [[language=C,]],
        [[basicstyle=\ttfamily,]],
        [[backgroundcolor=\color{blue!5},]],
        [[keywordstyle=\color{blue},]],
        [[commentstyle=\color{codegreen},]],
        [[stringstyle=\color{red},]],
        [[showstringspaces=false,]],
        [[breaklines=true,]],
        [[frame=single,]],
        [[rulecolor=\color{lightgray!35}, % Set the color of the frame]],
        [[numbers=none,]],
        [[numberstyle=\tiny,]],
        [[numbersep=5pt,]],
        [[tabsize=1,]],
        [[alsoletter={\#},]],
        [[otherkeywords={\#}]],
        [[}]],
        [[]],
        [[]],
        [[]],
        [[]],
        [[\lstdefinestyle{latexstyle}{]],
        [[language={[LaTeX]TeX},]],
        [[basicstyle=\ttfamily,]],
        [[backgroundcolor=\color{blue!5},]],
        [[keywordstyle=\color{blue},]],
        [[commentstyle=\color{codegreen},]],
        [[stringstyle=\color{red},]],
        [[showstringspaces=false,]],
        [[breaklines=true,]],
        [[frame=single,]],
        [[rulecolor=\color{lightgray!35}, % Set the color of the frame]],
        [[numbers=none,]],
        [[numberstyle=\tiny,]],
        [[numbersep=5pt,]],
        [[tabsize=1,]],
        [[morekeywords={documentclass, usepackage, begin, end},]],
        [[}]],
        [[]],
        [[]],
        [[%\input listings.tex]],
        [[]],
        [[]],
        [[]],
        [[% Define a command for inline code snippets with a colored and rounded box]],
        [[\newtcbox{\codebox}[1][gray]{on line, boxrule=0.2pt, colback=blue!5, colframe=#1, fontupper=\color{cherry}\ttfamily, arc=2pt, boxsep=0pt, left=2pt, right=2pt, top=3pt, bottom=2pt}]],
        [[]],
        [[%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%]],
        [[]],
        [[% Define a new tcolorbox style with default options for sections called Tips!]],
        [[\tcbset{]],
        [[myboxstyle/.style={]],
        [[colback=orange!10,]],
        [[colframe=orange!80!black,]],
        [[}]],
        [[}]],
        [[]],
        [[% Define a new tcolorbox style with default options to print the output with terminal style]],
        [[]],
        [[]],
        [[\tcbset{]],
        [[myboxstyleTerminal/.style={]],
        [[colback=blue!5,]],
        [[frame empty, % Set frame to empty to remove the fram]],
        [[}]],
        [[}]],
        [[]],
        [[\mdfdefinestyle{myboxstyleTerminal1}{]],
        [[backgroundcolor=blue!5,]],
        [[hidealllines=true, % Remove all lines (frame)]],
        [[leftline=false,     % Add a left line]],
        [[}]]
    }
)

ls.add_snippets("tex", {
    s("1XC3", { _1XC3_template })
})
